from django.core.management.base import BaseCommand, CommandError
from orariolezioni.models import *

class Command(BaseCommand):
    help = 'Popola il database con un buon numero di dati'

    def handle(self, *args, **options):
        f01 = facolta.objects.create(nome='Medicina', codice='MED-01')
        f02 = facolta.objects.create(nome='Economia', codice='ECO-01')
        f03 = facolta.objects.create(nome='Matematica', codice='MAT-01')
        f04 = facolta.objects.create(nome='Informatica', codice='MAT-03')
        f05 = facolta.objects.create(nome='Ingegneria Genetica', codice='ING-07')
        f06 = facolta.objects.create(nome='Ingegneria Informatica', codice='ING-04')


        d01 = docente.objects.create(nome='Stefania',
                                     cognome='Statis',
                                     email='stefaniastatis@universita.com',
                                     registration_key='OWUE5',
                                     giorno_libero='MER',
                                     giorno_impegnato='N.D',
                                     prima_delle_nove=False,
                                     dopo_le_cinque=False)
        d02 = docente.objects.create(nome='Stefano',
                                     cognome='Stati',
                                     email='stefanostati@universita.com',
                                     registration_key='9UEBR',
                                     giorno_libero='N.D',
                                     giorno_impegnato='N.D',
                                     prima_delle_nove=False,
                                     dopo_le_cinque=True)
        d03 = docente.objects.create(nome='Antonio',
                                     cognome='Antani',
                                     email='antonioantani@universita.com',
                                     registration_key='P5WE9',
                                     giorno_libero='LUN',
                                     giorno_impegnato='MAR',
                                     prima_delle_nove=True,
                                     dopo_le_cinque=False)
        d04 = docente.objects.create(nome='Fabrizio',
                                     cognome='Farmaci',
                                     email='fabriziofarmaci@universita.com',
                                     registration_key='N0782',
                                     giorno_libero='LUN',
                                     giorno_impegnato='GIO',
                                     prima_delle_nove=False,
                                     dopo_le_cinque=True)
        d05 = docente.objects.create(nome='John',
                                     cognome='Doe',
                                     email='johndoe@universita.com',
                                     registration_key='097S8',
                                     giorno_libero='LUN',
                                     giorno_impegnato='MAR',
                                     prima_delle_nove=True,
                                     dopo_le_cinque=True)
        d06 = docente.objects.create(nome='Ignazio',
                                     cognome='Informa',
                                     email='ignazioinforma@universita.com',
                                     registration_key='08BC3',
                                     giorno_libero='MER',
                                     giorno_impegnato='GIO',
                                     prima_delle_nove=True,
                                     dopo_le_cinque=False)
        d07 = docente.objects.create(nome='Anna',
                                     cognome='Lisi',
                                     email='annalisi@universita.com',
                                     registration_key='2I38B',
                                     giorno_libero='N.D',
                                     giorno_impegnato='N.D',
                                     prima_delle_nove=True,
                                     dopo_le_cinque=True)
        d08 = docente.objects.create(nome='Matteo',
                                     cognome='Matico',
                                     email='matteomatico@universita.com',
                                     registration_key='C3N9N',
                                     giorno_libero='GIO',
                                     giorno_impegnato='LUN',
                                     prima_delle_nove=False,
                                     dopo_le_cinque=True)
        d09 = docente.objects.create(nome='Aldo',
                                     cognome='Gebra',
                                     email='aldogebra@universita.com',
                                     registration_key='NDCWW',
                                     giorno_libero='VEN',
                                     giorno_impegnato='GIO',
                                     prima_delle_nove=False,
                                     dopo_le_cinque=False)
        d10 = docente.objects.create(nome='Pippo',
                                     cognome='Programmi',
                                     email='pippoprogrammi@universita.com',
                                     registration_key='MQD3I',
                                     giorno_libero='VEN',
                                     giorno_impegnato='GIO',
                                     prima_delle_nove=False,
                                     dopo_le_cinque=False)
        d11 = docente.objects.create(nome='Sisto',
                                     cognome='Temi',
                                     email='sistotemi@universita.com',
                                     registration_key='MAHD2',
                                     giorno_libero='VEN',
                                     giorno_impegnato='LUN',
                                     prima_delle_nove=True,
                                     dopo_le_cinque=False)
        d12 = docente.objects.create(nome='Margaret',
                                     cognome='Thatcher',
                                     email='margaretthatcher@universita.com',
                                     registration_key='X923U',
                                     giorno_libero='N.D',
                                     giorno_impegnato='N.D',
                                     prima_delle_nove=False,
                                     dopo_le_cinque=False)


        aula.objects.create(codice='MED01',
                            facolta=f01,
                            capienza=100,
                            laboratorio=False)
        aula.objects.create(codice='MED03',
                            facolta=f01,
                            capienza=50,
                            laboratorio=False)
        aula.objects.create(codice='MED04',
                            facolta=f01,
                            capienza=40,
                            laboratorio=False)
        aula.objects.create(codice='MED12',
                            facolta=f01,
                            capienza=60,
                            laboratorio=True)
        aula.objects.create(codice='MED13',
                            facolta=f01,
                            capienza=45,
                            laboratorio=True)
        aula.objects.create(codice='ECO-1',
                            facolta=f02,
                            capienza=80,
                            laboratorio=False)
        aula.objects.create(codice='ECO-2',
                            facolta=f02,
                            capienza=60,
                            laboratorio=False)
        aula.objects.create(codice='ECO-3',
                            facolta=f02,
                            capienza=40,
                            laboratorio=False)
        aula.objects.create(codice='ECO-L',
                            facolta=f02,
                            capienza=50,
                            laboratorio=True)
        aula.objects.create(codice='M-1/A',
                            facolta=f03,
                            capienza=100,
                            laboratorio=False)
        aula.objects.create(codice='M-1/B',
                            facolta=f03,
                            capienza=80,
                            laboratorio=False)
        aula.objects.create(codice='M-1/D',
                            facolta=f03,
                            capienza=25,
                            laboratorio=False)
        aula.objects.create(codice='M-2/F',
                            facolta=f03,
                            capienza=40,
                            laboratorio=True)
        aula.objects.create(codice='M-1/C',
                            facolta=f04,
                            capienza=60,
                            laboratorio=False)
        aula.objects.create(codice='M-1/E',
                            facolta=f04,
                            capienza=30,
                            laboratorio=False)
        aula.objects.create(codice='M-2/A',
                            facolta=f04,
                            capienza=50,
                            laboratorio=True)
        aula.objects.create(codice='M-2/B',
                            facolta=f04,
                            capienza=40,
                            laboratorio=True)
        aula.objects.create(codice='M-2/C',
                            facolta=f04,
                            capienza=30,
                            laboratorio=True)
        aula.objects.create(codice='ING01',
                            facolta=f05,
                            capienza=100,
                            laboratorio=False)
        aula.objects.create(codice='ING04',
                            facolta=f05,
                            capienza=50,
                            laboratorio=False)
        aula.objects.create(codice='ING05',
                            facolta=f05,
                            capienza=35,
                            laboratorio=True)
        aula.objects.create(codice='ING06',
                            facolta=f05,
                            capienza=40,
                            laboratorio=True)
        aula.objects.create(codice='ING02',
                            facolta=f06,
                            capienza=90,
                            laboratorio=False)
        aula.objects.create(codice='ING12',
                            facolta=f06,
                            capienza=60,
                            laboratorio=True)
        aula.objects.create(codice='ING13',
                            facolta=f06,
                            capienza=50,
                            laboratorio=True)
        aula.objects.create(codice='ING15',
                            facolta=f06,
                            capienza=30,
                            laboratorio=True)


        corso.objects.create(nome='Statistica',
                             docenti=d01,
                             facolta=f01,
                             crediti=2,
                             ore_settimanali=2,
                             ore_laboratorio=0,
                             numero_studenti=30)
        corso.objects.create(nome='Anatomia',
                             docenti=d03,
                             facolta=f01,
                             crediti=12,
                             ore_settimanali=10,
                             ore_laboratorio=4,
                             numero_studenti=60)
        corso.objects.create(nome='Farmacologia',
                             docenti=d04,
                             facolta=f01,
                             crediti=10,
                             ore_settimanali=8,
                             ore_laboratorio=6,
                             numero_studenti=30)
        corso.objects.create(nome='Inglese Tecnico',
                             docenti=d05,
                             facolta=f01,
                             crediti=3,
                             ore_settimanali=2,
                             ore_laboratorio=0,
                             numero_studenti=80)
        corso.objects.create(nome='Statistica',
                             docenti=d01,
                             facolta=f02,
                             crediti=10,
                             ore_settimanali=8,
                             ore_laboratorio=0,
                             numero_studenti=40)
        corso.objects.create(nome='Informatica',
                             docenti=d06,
                             facolta=f02,
                             crediti=6,
                             ore_settimanali=4,
                             ore_laboratorio=4,
                             numero_studenti=25)
        corso.objects.create(nome='Analisi Matematica',
                             docenti=d07,
                             facolta=f02,
                             crediti=10,
                             ore_settimanali=8,
                             ore_laboratorio=0,
                             numero_studenti=30)
        corso.objects.create(nome='Analisi Matematica',
                             docenti=d07,
                             facolta=f03,
                             crediti=15,
                             ore_settimanali=10,
                             ore_laboratorio=0,
                             numero_studenti=60)
        corso.objects.create(nome='Algebra Lineare',
                             docenti=d09,
                             facolta=f03,
                             crediti=9,
                             ore_settimanali=6,
                             ore_laboratorio=0,
                             numero_studenti=50)
        corso.objects.create(nome='Informatica',
                             docenti=d06,
                             facolta=f03,
                             crediti=6,
                             ore_settimanali=4,
                             ore_laboratorio=4,
                             numero_studenti=40)
        corso.objects.create(nome='Programmazione',
                             docenti=d10,
                             facolta=f04,
                             crediti=9,
                             ore_settimanali=6,
                             ore_laboratorio=6,
                             numero_studenti=40)
        corso.objects.create(nome='Sistemi Operativi',
                             docenti=d11,
                             facolta=f04,
                             crediti=9,
                             ore_settimanali=6,
                             ore_laboratorio=2,
                             numero_studenti=30)
        corso.objects.create(nome='Algebra Lineare',
                             docenti=d09,
                             facolta=f04,
                             crediti=9,
                             ore_settimanali=6,
                             ore_laboratorio=0,
                             numero_studenti=30)
        corso.objects.create(nome='Biologia',
                             docenti=d03,
                             facolta=f05,
                             crediti=6,
                             ore_settimanali=4,
                             ore_laboratorio=0,
                             numero_studenti=35)
        corso.objects.create(nome='Analisi Matematica',
                             docenti=d03,
                             facolta=f05,
                             crediti=9,
                             ore_settimanali=6,
                             ore_laboratorio=0,
                             numero_studenti=50)
        corso.objects.create(nome='Statistica',
                             docenti=d02,
                             facolta=f05,
                             crediti=9,
                             ore_settimanali=8,
                             ore_laboratorio=4,
                             numero_studenti=40)
        corso.objects.create(nome='Inglese Tecnico',
                             docenti=d05,
                             facolta=f05,
                             crediti=3,
                             ore_settimanali=4,
                             ore_laboratorio=0,
                             numero_studenti=50)
        corso.objects.create(nome='Sistemi Operativi',
                             docenti=d11,
                             facolta=f06,
                             crediti=9,
                             ore_settimanali=8,
                             ore_laboratorio=6,
                             numero_studenti=40)
        corso.objects.create(nome='Inglese',
                             docenti=d12,
                             facolta=f06,
                             crediti=3,
                             ore_settimanali=2,
                             ore_laboratorio=0,
                             numero_studenti=60)
        corso.objects.create(nome='Programmazione a Oggetti',
                             docenti=d06,
                             facolta=f06,
                             crediti=9,
                             ore_settimanali=6,
                             ore_laboratorio=6,
                             numero_studenti=50)
        corso.objects.create(nome='Matematica del Continuo',
                             docenti=d08,
                             facolta=f06,
                             crediti=9,
                             ore_settimanali=6,
                             ore_laboratorio=0,
                             numero_studenti=60)


        self.stdout.write(self.style.SUCCESS('Database popolato con successo!'))