# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 22:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aula',
            fields=[
                ('codice', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('capienza', models.PositiveIntegerField(default=25)),
                ('laboratorio', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'aule',
            },
        ),
        migrations.CreateModel(
            name='corso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('crediti', models.PositiveSmallIntegerField(default=0)),
                ('ore_settimanali', models.PositiveSmallIntegerField(default=0)),
                ('ore_laboratorio', models.PositiveSmallIntegerField(default=0)),
                ('numero_studenti', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'corsi',
            },
        ),
        migrations.CreateModel(
            name='docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('registration_key', models.CharField(default='', max_length=5, unique=True)),
                ('giorno_libero', models.CharField(choices=[('N.D', 'Indifferente'), ('LUN', 'Lunedì'), ('MAR', 'Martedì'), ('MER', 'Mercoledì'), ('GIO', 'Giovedì'), ('VEN', 'Venerdì')], default='N.D', max_length=3)),
                ('giorno_impegnato', models.CharField(choices=[('N.D', 'Indifferente'), ('LUN', 'Lunedì'), ('MAR', 'Martedì'), ('MER', 'Mercoledì'), ('GIO', 'Giovedì'), ('VEN', 'Venerdì')], default='N.D', max_length=3)),
                ('prima_delle_nove', models.BooleanField(default=False)),
                ('dopo_le_cinque', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'docenti',
            },
        ),
        migrations.CreateModel(
            name='facolta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('codice', models.CharField(default='AAA-00', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Inserisci un codice del tipo "AAA-00"', regex='[A-Z][A-Z][A-Z]-[\\d][\\d]')])),
            ],
            options={
                'verbose_name_plural': 'facoltà',
            },
        ),
        migrations.AlterUniqueTogether(
            name='docente',
            unique_together=set([('nome', 'cognome')]),
        ),
        migrations.AddField(
            model_name='corso',
            name='docenti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orariolezioni.docente'),
        ),
        migrations.AddField(
            model_name='corso',
            name='facolta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orariolezioni.facolta'),
        ),
        migrations.AddField(
            model_name='aula',
            name='facolta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orariolezioni.facolta'),
        ),
        migrations.AlterUniqueTogether(
            name='corso',
            unique_together=set([('nome', 'facolta')]),
        ),
    ]
